#ifndef __MOTORLIFTER_H
#define __MOTORLIFTER_H

#include "stm32f4xx_hal.h"

#define MOTOR_LIFTER_X_AXIS_MAX_SPEED   1024
#define MOTOR_LIFTER_Y_AXIS_MAX_SPEED   1024
#define MOTOR_LIFTER_Z_AXIS_MAX_SPEED   2048

#define MOTOR_LIFTER_X_AXIS_MIN_SPEED   512
#define MOTOR_LIFTER_Y_AXIS_MIN_SPEED   512
#define MOTOR_LIFTER_Z_AXIS_MIN_SPEED   1024

#define MOTOR_LIFTER_X_AXIS_ACCELERATION    256
#define MOTOR_LIFTER_Y_AXIS_ACCELERATION    256
#define MOTOR_LIFTER_Z_AXIS_ACCELERATION    256

#define MOTOR_LIFTER_X_AXIS_DECELERATION    256
#define MOTOR_LIFTER_Y_AXIS_DECELERATION    256
#define MOTOR_LIFTER_Z_AXIS_DECELERATION    1024

#define BSP_MOTOR_X_AXIS_BOUND_DETECT_GPIO GPIOA
#define BSP_MOTOR_X_AXIS_BOUND_DETECT_PIN  GPIO_PIN_0

#define BSP_MOTOR_Y_AXIS_BOUND_DETECT_GPIO GPIOA
#define BSP_MOTOR_Y_AXIS_BOUND_DETECT_PIN GPIO_PIN_1

enum MOTOR_LIFTER_AXIS_ID{
    MOTOR_LIFTER_X_AXIS_DEVICE_ID,
    MOTOR_LIFTER_Y_AXIS_DEVICE_ID,
    MOTOR_LIFTER_Z_AXIS_DEVICE_ID,
    MOTOR_LIFTER_XY_AXIS_DEVICE_ID_SELECT,
};

GPIO_PinState MotorLifter_XaxisBoundDetectGet(void);
GPIO_PinState MotorLifter_YaxisBoundDetectGet(void);

void MotorLifter_Init(void);

#endif
