#ifndef __MOTORLIFTER_H
#define __MOTORLIFTER_H

#include "stm32f4xx_hal.h"

#define BSP_MOTOR_X_AXIS_BOUND_DETECT_GPIO GPIOA
#define BSP_MOTOR_X_AXIS_BOUND_DETECT_PIN  GPIO_PIN_0

#define BSP_MOTOR_Y_AXIS_BOUND_DETECT_GPIO GPIOA
#define BSP_MOTOR_Y_AXIS_BOUND_DETECT_PIN GPIO_PIN_1

#define BSP_MOTOR_Z_AXIS_BOUND_DETECT_GPIO GPIOA
#define BSP_MOTOR_Z_AXIS_BOUND_DETECT_PIN GPIO_PIN_4

enum MOTOR_LIFTER_AXIS_ID{
    MOTOR_LIFTER_X_AXIS_DEVICE_ID,
    MOTOR_LIFTER_Y_AXIS_DEVICE_ID,
    MOTOR_LIFTER_Z_AXIS_DEVICE_ID,
    MOTOR_LIFTER_AXIS_DEVICE_ID_BOUND,
};

GPIO_PinState MotorLifter_XaxisBoundDetectGet(void);
GPIO_PinState MotorLifter_YaxisBoundDetectGet(void);
GPIO_PinState MotorLifter_ZaxisBoundDetectGet(void);

void MotorLifter_Init(void);

#endif
